# Generated by Django 4.2.18 on 2026-04-10 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Timestamp of the user's most recent authenticated API request. Updated by OnlinePresenceMiddleware — not set manually.", null=True, verbose_name='Last activity'),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'User Created'), ('updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('activated', 'Account Activated'), ('deactivated', 'Account Deactivated'), ('deleted', 'Account Deleted'), ('role_changed', 'Role Changed'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('failed_login', 'Failed Login Attempt')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, help_text='Arbitrary before/after values. MUST NEVER contain passwords or tokens.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin who triggered this action. Null if the account was deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed by')),
                ('subject', models.ForeignKey(blank=True, help_text='User account this action was performed on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log', to=settings.AUTH_USER_MODEL, verbose_name='Target user')),
            ],
            options={
                'verbose_name': 'User Audit Log',
                'verbose_name_plural': 'User Audit Logs',
                'db_table': 'users_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='users_audit_actor_i_d13085_idx'), models.Index(fields=['subject', 'created_at'], name='users_audit_subject_05aee8_idx'), models.Index(fields=['action', 'created_at'], name='users_audit_action_38fd93_idx')],
            },
        ),
    ]
