# Generated by Django 4.2.18 on 2026-05-15 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_application_ai_parsed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skills_match', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_match', models.DecimalField(decimal_places=2, max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extracted_skills', models.JSONField(blank=True, null=True)),
                ('extracted_experience', models.SmallIntegerField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('gaps', models.JSONField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('model_version', models.CharField(max_length=20)),
                ('error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score_detail', to='applications.application')),
            ],
            options={
                'verbose_name': 'Candidate Score',
                'verbose_name_plural': 'Candidate Scores',
                'ordering': ['-match_score'],
            },
        ),
    ]
