# Generated by Django 4.2.18 on 2026-04-20 02:33
# Hand-edited to backfill slugs on existing rows before adding UNIQUE constraint.

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    """Generate a unique slug for every existing Job row."""
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all():
        base = slugify(job.title) or 'job'
        job.slug = f"{base}-{uuid.uuid4().hex[:8]}"
        job.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        # Step 1: add the column as nullable/non-unique so existing rows are safe
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, default=''),
            preserve_default=False,
        ),
        # Step 2: fill slugs for all existing rows
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # Step 3: add the unique constraint now that all rows have distinct values
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
