# Generated by Django 4.2.18 on 2026-05-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
