# Generated by Django 4.2.18 on 2026-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_ai_parsed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_status_msg',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
