# Generated by Django 4.2.18 on 2026-05-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_ai_status_application_ai_status_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ai_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ai_status_msg',
        ),
    ]
